VARIANT_DB = {
    "17203": {
        "brand": "VW",
        "platform": "ZR",
        "region": "EU",
        "navi": "no",
        "dab": "no",
    },
    "17204": {
        "brand": "VW",
        "platform": "ZR",
        "region": "EU",
        "navi": "no",
        "dab": "yes",
    },
    "17205": {
        "brand": "VW",
        "platform": "ZR",
        "region": "EU",
        "navi": "no",
        "dab": "no",
    },
    "17206": {
        "brand": "VW",
        "platform": "ZR",
        "region": "EU",
        "navi": "yes",
        "dab": "yes",
    },
    "17207": {
        "brand": "VW",
        "platform": "ZR",
        "region": "EU",
        "navi": "yes",
        "dab": "no",
    },
    "17224": {
        "brand": "VW",
        "platform": "ZR",
        "region": "EU",
        "navi": "yes",
        "dab": "no",
    },
    "17210": {
        "brand": "VW",
        "platform": "ZR",
        "region": "US",
        "navi": "yes",
        "dab": "yes",
    },
    "17212": {
        "brand": "VW",
        "platform": "ZR",
        "region": "CN",
        "navi": "yes",
        "dab": "no",
    },
    "17214": {
        "brand": "VW",
        "platform": "PQ",
        "region": "EU",
        "navi": "no",
        "dab": "yes",
    },
    "17215": {
        "brand": "VW",
        "platform": "PQ",
        "region": "EU",
        "navi": "no",
        "dab": "no",
    },
    "17216": {
        "brand": "VW",
        "platform": "PQ",
        "region": "EU",
        "navi": "yes",
        "dab": "yes",
    },
    "17217": {
        "brand": "VW",
        "platform": "PQ",
        "region": "EU",
        "navi": "yes",
        "dab": "no",
    },
    "17218": {
        "brand": "VW",
        "platform": "PQ",
        "region": "USA",
        "navi": "no",
        "dab": "yes",
    },
    "17219": {
        "brand": "VW",
        "platform": "PQ",
        "region": "USA",
        "navi": "no",
        "dab": "yes",
    },
    "17220": {
        "brand": "VW",
        "platform": "PQ",
        "region": "USA",
        "navi": "yes",
        "dab": "yes",
    },
    "17221": {
        "brand": "VW",
        "platform": "PQ",
        "region": "USA",
        "navi": "yes",
        "dab": "yes",
    },
    "17222": {
        "brand": "VW",
        "platform": "PQ",
        "region": "CN",
        "navi": "yes",
        "dab": "no",
    },
    "17223": {
        "brand": "VW",
        "platform": "PQ",
        "region": "RoA",
        "navi": "no",
        "dab": "no",
    },
    "17225": {
        "brand": "VW",
        "platform": "PQ",
        "region": "EU",
        "navi": "yes",
        "dab": "no",
    },
    "47201": {
        "brand": "SEAT",
        "platform": "ZR",
        "region": "EU",
        "navi": "no",
        "dab": "yes",
    },
    "47202": {
        "brand": "SEAT",
        "platform": "ZR",
        "region": "EU",
        "navi": "no",
        "dab": "no",
    },
    "47203": {
        "brand": "SEAT",
        "platform": "ZR",
        "region": "EU",
        "navi": "yes",
        "dab": "yes",
    },
    "47204": {
        "brand": "SEAT",
        "platform": "ZR",
        "region": "EU",
        "navi": "yes",
        "dab": "no",
    },
    "47213": {
        "brand": "SEAT",
        "platform": "ZR",
        "region": "EU",
        "navi": "no",
        "dab": "yes",
    },
    "47214": {
        "brand": "SEAT",
        "platform": "ZR",
        "region": "EU",
        "navi": "yes",
        "dab": "yes",
    },
    "47206": {
        "brand": "SEAT",
        "platform": "PQ",
        "region": "EU",
        "navi": "no",
        "dab": "yes",
    },
    "47207": {
        "brand": "SEAT",
        "platform": "PQ",
        "region": "EU",
        "navi": "no",
        "dab": "no",
    },
    "47208": {
        "brand": "SEAT",
        "platform": "PQ",
        "region": "EU",
        "navi": "yes",
        "dab": "yes",
    },
    "47209": {
        "brand": "SEAT",
        "platform": "PQ",
        "region": "EU",
        "navi": "yes",
        "dab": "no",
    },
    "37204": {
        "brand": "Skoda",
        "platform": "ZR",
        "region": "EU",
        "navi": "no",
        "dab": "yes",
    },
    "37205": {
        "brand": "Skoda",
        "platform": "ZR",
        "region": "EU",
        "navi": "no",
        "dab": "no",
    },
    "37206": {
        "brand": "Skoda",
        "platform": "ZR",
        "region": "EU",
        "navi": "yes",
        "dab": "yes",
    },
    "37207": {
        "brand": "Skoda",
        "platform": "ZR",
        "region": "EU",
        "navi": "yes",
        "dab": "no",
    },
    "37214": {
        "brand": "Skoda",
        "platform": "ZR",
        "region": "CN",
        "navi": "yes",
        "dab": "no",
    },
    "37210": {
        "brand": "Skoda",
        "platform": "PQ",
        "region": "EU",
        "navi": "no",
        "dab": "no",
    },
    "37211": {
        "brand": "Skoda",
        "platform": "PQ",
        "region": "EU",
        "navi": "no",
        "dab": "yes",
    },
    "37212": {
        "brand": "Skoda",
        "platform": "PQ",
        "region": "EU",
        "navi": "yes",
        "dab": "no",
    },
    "37213": {
        "brand": "Skoda",
        "platform": "PQ",
        "region": "EU",
        "navi": "yes",
        "dab": "yes",
    },
}
